import { defineConfig } from "wxt";

export default defineConfig({
  // MV3 manifest is generated by WXT from entrypoints and this config
  manifest: {
    name: "Qwen Chat with Superpowers",
    description:
      "Local-first Qwen Chat: folders, search, prompt manager, image gallery, voice, export, chains, and more.",
    version: "0.1.0",
    action: {
      default_title: "Qwen Chat",
      default_popup: "popup.html",
    },
    side_panel: {
      default_path: "sidepanel.html",
      openPanelOnActionClick: false,
    },
    options_ui: {
      page: "options.html",
      open_in_tab: true,
    },
    permissions: [
      "storage",
      "contextMenus",
      "activeTab",
      "tabs"
    ],
    host_permissions: [
      "<all_urls>"
    ],
  },
});


